# Foundations: Potential Outcomes

> ## Class materials
>
> Slides: [**Module 1**](https://drive.google.com/file/d/1ujOsEenrQy1sjIX4Zt_CfAqeF0o-KfY-/view?usp=sharing)
>
> Recording: [**Module 1, Part 1.1**](https://drive.google.com/file/d/14yxdT8so1w2LQV2pwoGm1ys3Ek5yuLET/view?usp=sharing)
>
> Recording: [**Module 1, Part 2.1**](https://drive.google.com/file/d/1rUQnbOTkVk5DPu8Ghbu2W80NJ008Auyt/view?usp=sharing)
>
> Recording: [**Module 1, Part 2.2**](https://drive.google.com/file/d/1hsA1CZ0jpVycsNmuH0A7C5AHmlvBpOvM/view?usp=sharing)

> ## Textbook reading 
>
> [**Chapters 1 -- 3 of Imbens and Rubin (2015)**](https://www.cambridge.org/core/books/causal-inference-for-statistics-social-and-biomedical-sciences/71126BE90C58F1A431FE9B2DD07938AB)
>
> [**Chapters 1--2 of Ding (2023)**](https://www.routledge.com/A-First-Course-in-Causal-Inference/Ding/p/book/9781032758626)

> ### Review papers on the Potential Outcomes approach
>
> [**Holland, P. (1986)**](https://www.jstor.org/stable/2289064) "Statistics and Causal Inference" (with discussion), Journal of the American Statistical Association, 81:945-970.
> - [D.B. Rubin discussion](https://www.jstor.org/stable/2289065)
> - [D.R. Cox discussion](https://www.jstor.org/stable/2289066)
> - [C. Glymour discussion](https://www.jstor.org/stable/2289067)
> - [C. Granger discussion](https://www.jstor.org/stable/2289068)
> - [P. Holland rejoinder](https://www.jstor.org/stable/2289069)
>
> [**Rosenbaum, P.R. (1995)**](https://www.jstor.org/stable/2337336) "Discussion of 'Causal diagrams for empirical research' by J. Pearl," Biometrika, 82: 698-699.
>
> [**Little, R.J.A., Rubin, D.B. (2000)**](http://www.annualreviews.org/doi/full/10.1146/annurev.publhealth.21.1.121) "Causal Effects in Clinical and Epidemiological Studies via Potential Outcomes: Concepts and Analytical Approaches," Annual Review of Public Health, 21:121-145.
>
> [**Rubin, D.B. (2005)**](https://www.jstor.org/stable/27590541) "Causal inference using potential outcomes: Design, modeling, decisions," Journal of the American Statistical Association, 100, 322-331.
>
> [**Hernan, MA (2016)**](https://www.sciencedirect.com/science/article/abs/pii/S1047279716302800?via%3Dihub) "Does Water Kill?", Annals of Epidemiology, 26(10)
>
> [**Dominici F, Bargagli-Stoffi FJ, Mealli F (2021)**](https://hdsr.mitpress.mit.edu/pub/hdzphsk6/release/5)"From Controlled to Undisciplined Data: Estimating Causal Effects in the Era of Data Science Using a Potential Outcome Framework, Harvard Data Science Review, 3(3).

> ### Seminal papers on the Potential Outcomes approach
>
> [**Neyman, J. (1923)**](https://www.jstor.org/stable/2245382) "On the Application of Probability Theory to Agricultural Experiments. Essay on Principles. Section 9." (translated and edited by D.M. Dabrowska and T.P. Speed, with discussion), in Statistical Science (1990), 5:463-472.
> - [Introduction by T.P. Speed, Editor, Statistical Science](https://www.jstor.org/stable/2245381)
>
> [**Rubin, D.B. (1974)**](https://www.semanticscholar.org/paper/Estimating-causal-effects-of-treatments-in-and-Rubin/22e2990590524459ec9b59ccac6ce71e3b6a) "Estimating Causal Effects of Treatments in Randomized and Nonrandomized Studies," Journal of Educational Psychology, 1974; 66: 688-701. [open access]
>
> [**Rubin, D.B. (1978)**](https://www.jstor.org/stable/2958688) "Bayesian Inference for Causal Effects: The Role of Randomization," Annals of Statistics, 6:34-58.
>
> [**Rubin, D.B. (1990)**](https://www.jstor.org/stable/2245383) "Comment: Neyman (1923) and Causal Inference in Experiments and Observational Studies," Statistical Science, 5: 472-480.





