<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>4 Effect Modification and Interaction | Causal-Inference-Graduate.knit</title>
  <meta name="description" content="An undergraduate course on causal inference" />
  <meta name="generator" content="bookdown 0.43 and GitBook 2.6.7" />

  <meta property="og:title" content="4 Effect Modification and Interaction | Causal-Inference-Graduate.knit" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="An undergraduate course on causal inference" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="4 Effect Modification and Interaction | Causal-Inference-Graduate.knit" />
  
  <meta name="twitter:description" content="An undergraduate course on causal inference" />
  




  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="observational-studies.html"/>
<link rel="next" href="introduction-to-causal-diagrams.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Causal Inference</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Welcome</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#course-description"><i class="fa fa-check"></i>Course Description</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#instructor"><i class="fa fa-check"></i>Instructor</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#teaching-assistants"><i class="fa fa-check"></i>Teaching Assistants</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#course-logistics"><i class="fa fa-check"></i>Course Logistics</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#required-materials"><i class="fa fa-check"></i>Required Materials</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#learning-objectives"><i class="fa fa-check"></i>Learning Objectives</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#upon-successful-completion-of-this-course-students-will-be-able-to"><i class="fa fa-check"></i>Upon successful completion of this course, students will be able to:</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#tools"><i class="fa fa-check"></i>Tools</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#useful-links"><i class="fa fa-check"></i>Useful Links</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="setup.html"><a href="setup.html"><i class="fa fa-check"></i>Setup</a>
<ul>
<li class="chapter" data-level="" data-path="setup.html"><a href="setup.html#installing-and-using-required-packages"><i class="fa fa-check"></i>Installing and Using Required Packages</a></li>
<li class="chapter" data-level="" data-path="setup.html"><a href="setup.html#loading-packages"><i class="fa fa-check"></i>Loading Packages</a></li>
<li class="chapter" data-level="" data-path="setup.html"><a href="setup.html#difference-between-install.packages-and-library"><i class="fa fa-check"></i>Difference Between install.packages() and library()</a></li>
<li class="chapter" data-level="" data-path="setup.html"><a href="setup.html#session-information"><i class="fa fa-check"></i>Session Information</a></li>
<li class="chapter" data-level="" data-path="setup.html"><a href="setup.html#why-include-this"><i class="fa fa-check"></i>Why include this?</a></li>
<li class="chapter" data-level="" data-path="setup.html"><a href="setup.html#base-r-version-simple"><i class="fa fa-check"></i>Base R version (simple)</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="causal-dictionary.html"><a href="causal-dictionary.html"><i class="fa fa-check"></i>Causal Dictionary</a></li>
<li class="chapter" data-level="1" data-path="foundations-of-causal-thinking-in-public-health.html"><a href="foundations-of-causal-thinking-in-public-health.html"><i class="fa fa-check"></i><b>1</b> Foundations of Causal Thinking in Public Health</a>
<ul>
<li class="chapter" data-level="1.1" data-path="foundations-of-causal-thinking-in-public-health.html"><a href="foundations-of-causal-thinking-in-public-health.html#association-vs.-causation"><i class="fa fa-check"></i><b>1.1</b> Association vs. Causation</a></li>
<li class="chapter" data-level="1.2" data-path="foundations-of-causal-thinking-in-public-health.html"><a href="foundations-of-causal-thinking-in-public-health.html#introduction-to-counterfactuals-and-potential-outcomes"><i class="fa fa-check"></i><b>1.2</b> Introduction to Counterfactuals and Potential Outcomes</a></li>
<li class="chapter" data-level="1.3" data-path="foundations-of-causal-thinking-in-public-health.html"><a href="foundations-of-causal-thinking-in-public-health.html#causal-estimands-and-identification"><i class="fa fa-check"></i><b>1.3</b> Causal Estimands and Identification</a></li>
<li class="chapter" data-level="1.4" data-path="foundations-of-causal-thinking-in-public-health.html"><a href="foundations-of-causal-thinking-in-public-health.html#measuring-effects-for-binary-outcomes"><i class="fa fa-check"></i><b>1.4</b> Measuring Effects for Binary Outcomes</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="randomized-control-trials.html"><a href="randomized-control-trials.html"><i class="fa fa-check"></i><b>2</b> Randomized Control Trials</a>
<ul>
<li class="chapter" data-level="2.1" data-path="randomized-control-trials.html"><a href="randomized-control-trials.html#randomized-controlled-trials-the-gold-standard"><i class="fa fa-check"></i><b>2.1</b> Randomized controlled trials: the gold standard</a></li>
<li class="chapter" data-level="2.2" data-path="randomized-control-trials.html"><a href="randomized-control-trials.html#basic-experimental-design-principles"><i class="fa fa-check"></i><b>2.2</b> Basic Experimental Design Principles</a></li>
<li class="chapter" data-level="2.3" data-path="randomized-control-trials.html"><a href="randomized-control-trials.html#limitations-of-rcts-in-public-health-contexts"><i class="fa fa-check"></i><b>2.3</b> Limitations of RCTs in Public Health Contexts</a></li>
<li class="chapter" data-level="2.4" data-path="randomized-control-trials.html"><a href="randomized-control-trials.html#common-threats-to-internal-and-external-validity"><i class="fa fa-check"></i><b>2.4</b> Common Threats to Internal and External Validity</a></li>
<li class="chapter" data-level="2.5" data-path="randomized-control-trials.html"><a href="randomized-control-trials.html#causal-quantities-sate-vs-pate"><i class="fa fa-check"></i><b>2.5</b> Causal Quantities: SATE vs PATE</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="observational-studies.html"><a href="observational-studies.html"><i class="fa fa-check"></i><b>3</b> Observational Studies</a>
<ul>
<li class="chapter" data-level="3.1" data-path="observational-studies.html"><a href="observational-studies.html#the-challenge-of-confounding-in-public-health-and-medical-research"><i class="fa fa-check"></i><b>3.1</b> The challenge of confounding in public health and medical research</a></li>
<li class="chapter" data-level="3.2" data-path="observational-studies.html"><a href="observational-studies.html#exchangeability-positivity-and-sutva"><i class="fa fa-check"></i><b>3.2</b> Exchangeability, positivity, and SUTVA</a></li>
<li class="chapter" data-level="3.3" data-path="observational-studies.html"><a href="observational-studies.html#effect-identification-in-observational-studies"><i class="fa fa-check"></i><b>3.3</b> Effect Identification in Observational Studies</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="effect-modification-and-interaction.html"><a href="effect-modification-and-interaction.html"><i class="fa fa-check"></i><b>4</b> Effect Modification and Interaction</a>
<ul>
<li class="chapter" data-level="4.1" data-path="effect-modification-and-interaction.html"><a href="effect-modification-and-interaction.html#effect-modification-and-adjustment-methods"><i class="fa fa-check"></i><b>4.1</b> Effect Modification and Adjustment Methods</a></li>
<li class="chapter" data-level="4.2" data-path="effect-modification-and-interaction.html"><a href="effect-modification-and-interaction.html#interaction"><i class="fa fa-check"></i><b>4.2</b> Interaction</a></li>
<li class="chapter" data-level="4.3" data-path="effect-modification-and-interaction.html"><a href="effect-modification-and-interaction.html#identifying-interaction"><i class="fa fa-check"></i><b>4.3</b> Identifying Interaction</a></li>
<li class="chapter" data-level="4.4" data-path="effect-modification-and-interaction.html"><a href="effect-modification-and-interaction.html#effect-modification-vs-interaction"><i class="fa fa-check"></i><b>4.4</b> Effect Modification vs Interaction</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="introduction-to-causal-diagrams.html"><a href="introduction-to-causal-diagrams.html"><i class="fa fa-check"></i><b>5</b> Introduction to Causal Diagrams</a>
<ul>
<li class="chapter" data-level="5.1" data-path="introduction-to-causal-diagrams.html"><a href="introduction-to-causal-diagrams.html#basic-principles-of-directed-acyclic-graphs-dags"><i class="fa fa-check"></i><b>5.1</b> Basic principles of directed acyclic graphs (DAGs)</a></li>
<li class="chapter" data-level="5.2" data-path="introduction-to-causal-diagrams.html"><a href="introduction-to-causal-diagrams.html#common-causal-structures-in-public-health"><i class="fa fa-check"></i><b>5.2</b> Common Causal Structures in Public Health</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="confounding-and-selection-bias.html"><a href="confounding-and-selection-bias.html"><i class="fa fa-check"></i><b>6</b> Confounding and Selection Bias</a>
<ul>
<li class="chapter" data-level="6.1" data-path="confounding-and-selection-bias.html"><a href="confounding-and-selection-bias.html#the-form-of-selection-bias"><i class="fa fa-check"></i><b>6.1</b> The Form of Selection Bias</a></li>
<li class="chapter" data-level="6.2" data-path="confounding-and-selection-bias.html"><a href="confounding-and-selection-bias.html#how-to-adjust-for-selection-bias"><i class="fa fa-check"></i><b>6.2</b> How to Adjust for Selection Bias</a></li>
<li class="chapter" data-level="6.3" data-path="confounding-and-selection-bias.html"><a href="confounding-and-selection-bias.html#the-structure-of-confounding"><i class="fa fa-check"></i><b>6.3</b> The Structure of Confounding</a></li>
<li class="chapter" data-level="6.4" data-path="confounding-and-selection-bias.html"><a href="confounding-and-selection-bias.html#how-to-adjust-for-confounding"><i class="fa fa-check"></i><b>6.4</b> How to Adjust for Confounding</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="other-common-pitfalls-of-causal-analyses.html"><a href="other-common-pitfalls-of-causal-analyses.html"><i class="fa fa-check"></i><b>7</b> Other Common Pitfalls of Causal Analyses</a>
<ul>
<li class="chapter" data-level="7.1" data-path="other-common-pitfalls-of-causal-analyses.html"><a href="other-common-pitfalls-of-causal-analyses.html#measurement-bias"><i class="fa fa-check"></i><b>7.1</b> Measurement Bias</a></li>
<li class="chapter" data-level="7.2" data-path="other-common-pitfalls-of-causal-analyses.html"><a href="other-common-pitfalls-of-causal-analyses.html#non-compliance"><i class="fa fa-check"></i><b>7.2</b> Non-compliance</a></li>
<li class="chapter" data-level="7.3" data-path="other-common-pitfalls-of-causal-analyses.html"><a href="other-common-pitfalls-of-causal-analyses.html#non-causal-diagrams"><i class="fa fa-check"></i><b>7.3</b> Non-Causal Diagrams</a></li>
<li class="chapter" data-level="7.4" data-path="other-common-pitfalls-of-causal-analyses.html"><a href="other-common-pitfalls-of-causal-analyses.html#publication-bias-and-p-hacking"><i class="fa fa-check"></i><b>7.4</b> Publication Bias and P-Hacking</a></li>
<li class="chapter" data-level="7.5" data-path="other-common-pitfalls-of-causal-analyses.html"><a href="other-common-pitfalls-of-causal-analyses.html#over--and-mis-interpretation-of-statistical-analyses"><i class="fa fa-check"></i><b>7.5</b> Over- and Mis-Interpretation of Statistical Analyses</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="from-identification-to-estimation.html"><a href="from-identification-to-estimation.html"><i class="fa fa-check"></i><b>8</b> From Identification to Estimation</a>
<ul>
<li class="chapter" data-level="8.1" data-path="from-identification-to-estimation.html"><a href="from-identification-to-estimation.html#identification-and-estimation"><i class="fa fa-check"></i><b>8.1</b> Identification and Estimation</a></li>
<li class="chapter" data-level="8.2" data-path="from-identification-to-estimation.html"><a href="from-identification-to-estimation.html#estimation-of-causal-effects"><i class="fa fa-check"></i><b>8.2</b> Estimation of causal effects</a></li>
<li class="chapter" data-level="8.3" data-path="from-identification-to-estimation.html"><a href="from-identification-to-estimation.html#taxonomy-of-estimation-models"><i class="fa fa-check"></i><b>8.3</b> Taxonomy of estimation models</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="applications-of-causal-inference-in-public-health-and-medical-research.html"><a href="applications-of-causal-inference-in-public-health-and-medical-research.html"><i class="fa fa-check"></i><b>9</b> Applications of Causal Inference in Public Health and Medical Research</a>
<ul>
<li class="chapter" data-level="9.1" data-path="applications-of-causal-inference-in-public-health-and-medical-research.html"><a href="applications-of-causal-inference-in-public-health-and-medical-research.html#public-health-policy-evaluation"><i class="fa fa-check"></i><b>9.1</b> Public health policy evaluation</a></li>
<li class="chapter" data-level="9.2" data-path="applications-of-causal-inference-in-public-health-and-medical-research.html"><a href="applications-of-causal-inference-in-public-health-and-medical-research.html#environmental-exposure-studies"><i class="fa fa-check"></i><b>9.2</b> Environmental exposure studies</a></li>
<li class="chapter" data-level="9.3" data-path="applications-of-causal-inference-in-public-health-and-medical-research.html"><a href="applications-of-causal-inference-in-public-health-and-medical-research.html#health-disparities-research"><i class="fa fa-check"></i><b>9.3</b> Health disparities research</a></li>
<li class="chapter" data-level="9.4" data-path="applications-of-causal-inference-in-public-health-and-medical-research.html"><a href="applications-of-causal-inference-in-public-health-and-medical-research.html#prevention-program-evaluation"><i class="fa fa-check"></i><b>9.4</b> Prevention program evaluation</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="presentation-of-final-projects.html"><a href="presentation-of-final-projects.html"><i class="fa fa-check"></i><b>10</b> Presentation of Final Projects</a>
<ul>
<li class="chapter" data-level="10.1" data-path="presentation-of-final-projects.html"><a href="presentation-of-final-projects.html#final-project"><i class="fa fa-check"></i><b>10.1</b> Final Project</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://www.falcobargaglistoffi.com/" target="blank">Instructor: Falco J. Bargagli-Stoffi</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./"></a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="effect-modification-and-interaction" class="section level1 hasAnchor" number="4">
<h1><span class="header-section-number">4</span> Effect Modification and Interaction<a href="effect-modification-and-interaction.html#effect-modification-and-interaction" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<blockquote>
<h2 id="class-materials-3" class="hasAnchor">Class materials<a href="effect-modification-and-interaction.html#class-materials-3" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Slides: <a href="https://drive.google.com/drive/folders/14Iymvk2FlZqVsWrtbDLmwSzR5aNS-Mcg?usp=sharing"><strong>Module 4</strong></a></p>
<p>Recording: <a href="https://your-recording-link.com"><strong>Module 4, Part 1</strong></a></p>
<p>Recording: <a href="https://your-recording-link.com"><strong>Module 4, Part 2</strong></a></p>
</blockquote>
<blockquote>
<h2 id="textbook-reading-3" class="hasAnchor">Textbook reading<a href="effect-modification-and-interaction.html#textbook-reading-3" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p><a href="https://static1.squarespace.com/static/675db8b0dd37046447128f5f/t/677676888e31cc50c2c33877/1735816881944/hernanrobins_WhatIf_2jan25.pdf"><strong>Hernán &amp; Robins, Causal Inference: What If – Chapters 4–5</strong></a></p>
</blockquote>
<blockquote>
<h2 id="supplementary-reading-3" class="hasAnchor">Supplementary reading<a href="effect-modification-and-interaction.html#supplementary-reading-3" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p><a href="https://rss.onlinelibrary.wiley.com/doi/full/10.1111/j.1467-985X.2007.00500.x"><strong>Freedman, D. A. (2008). On types of scientific inquiry: The role of RCTs in health policy. Journal of the Royal Statistical Society: Series A, 171(2), 359–385.</strong></a>  Examples of quasi-experiments from public health and education</p>
</blockquote>
<blockquote>
<h2 id="topics-covered-3" class="hasAnchor">Topics covered<a href="effect-modification-and-interaction.html#topics-covered-3" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<ul>
<li>Effect modification and adjustment methods<br />
</li>
<li>Interaction<br />
</li>
<li>Identifying interaction<br />
</li>
<li>Effect modification vs interaction<br />
</li>
<li>Critical reading exercise: evaluating effect modification and interaction in studies</li>
</ul>
</blockquote>
<div id="effect-modification-and-adjustment-methods" class="section level2 hasAnchor" number="4.1">
<h2><span class="header-section-number">4.1</span> Effect Modification and Adjustment Methods<a href="effect-modification-and-interaction.html#effect-modification-and-adjustment-methods" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Effect modification occurs when the effect of an exposure on an outcome differs depending on the level of another variable. Unlike confounding, which biases the estimated effect, effect modification reflects a real variation in the causal effect across different subgroups. Recognizing effect modification is important because it can reveal that a treatment or exposure is beneficial for some groups but not for others. Adjustment methods like stratification or including interaction terms in regression models help detect and describe effect modification rather than “control” it away. When we study effect modification, we are asking causal questions such as “What the effect of a treatment for group 1 vs the effect for group 2?”</p>
<p>Adjustment methods typically aim to control for confounding, but they can also be used to detect effect modification when interaction terms are included. When effect modification is present, a single summary effect estimate (like an overall average) can be misleading. Instead, researchers often report subgroup-specific effects. Careful modeling and interpretation are necessary to distinguish between true effect modification and residual confounding.</p>
<p>Simulation to Demonstrate Effect Modification</p>
<p>Let’s say we are interested in understanding the effect of new drug on a person’s VO2 max for young vs old people. For example, this drug might be more effective for young people. VO2 max is the maximum amount of oxygen your body can utilize during exercise. VO2 max is measured in mL per kg of body weight per minute. In this simulation, the drug increases VO2 max by 4 mL/kg/min for old people, and 7.5 mL/kg/min for young people.</p>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="effect-modification-and-interaction.html#cb39-1" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb39-2"><a href="effect-modification-and-interaction.html#cb39-2" tabindex="-1"></a></span>
<span id="cb39-3"><a href="effect-modification-and-interaction.html#cb39-3" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">2000</span></span>
<span id="cb39-4"><a href="effect-modification-and-interaction.html#cb39-4" tabindex="-1"></a></span>
<span id="cb39-5"><a href="effect-modification-and-interaction.html#cb39-5" tabindex="-1"></a>treatment <span class="ot">&lt;-</span> <span class="fu">rbinom</span>(n, <span class="dv">1</span>, <span class="fl">0.5</span>) <span class="co"># drug</span></span>
<span id="cb39-6"><a href="effect-modification-and-interaction.html#cb39-6" tabindex="-1"></a></span>
<span id="cb39-7"><a href="effect-modification-and-interaction.html#cb39-7" tabindex="-1"></a>age_group <span class="ot">&lt;-</span> <span class="fu">rbinom</span>(n, <span class="dv">1</span>, <span class="fl">0.5</span>) <span class="co"># 1 = young, 0 = old</span></span>
<span id="cb39-8"><a href="effect-modification-and-interaction.html#cb39-8" tabindex="-1"></a></span>
<span id="cb39-9"><a href="effect-modification-and-interaction.html#cb39-9" tabindex="-1"></a>baseline <span class="ot">&lt;-</span> <span class="dv">35</span> <span class="co"># baseline VO2 max is 35 mL/kg/min</span></span>
<span id="cb39-10"><a href="effect-modification-and-interaction.html#cb39-10" tabindex="-1"></a></span>
<span id="cb39-11"><a href="effect-modification-and-interaction.html#cb39-11" tabindex="-1"></a>vo2_max <span class="ot">&lt;-</span> baseline <span class="sc">+</span> </span>
<span id="cb39-12"><a href="effect-modification-and-interaction.html#cb39-12" tabindex="-1"></a>            <span class="dv">4</span> <span class="sc">*</span> treatment <span class="sc">+</span> </span>
<span id="cb39-13"><a href="effect-modification-and-interaction.html#cb39-13" tabindex="-1"></a>            <span class="fl">0.5</span> <span class="sc">*</span> age_group <span class="sc">+</span> </span>
<span id="cb39-14"><a href="effect-modification-and-interaction.html#cb39-14" tabindex="-1"></a>            <span class="fl">3.5</span> <span class="sc">*</span> (treatment <span class="sc">*</span> age_group) <span class="sc">+</span> </span>
<span id="cb39-15"><a href="effect-modification-and-interaction.html#cb39-15" tabindex="-1"></a>            <span class="fu">rnorm</span>(n, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">1</span>)</span>
<span id="cb39-16"><a href="effect-modification-and-interaction.html#cb39-16" tabindex="-1"></a></span>
<span id="cb39-17"><a href="effect-modification-and-interaction.html#cb39-17" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(vo2_max, treatment, age_group)</span>
<span id="cb39-18"><a href="effect-modification-and-interaction.html#cb39-18" tabindex="-1"></a></span>
<span id="cb39-19"><a href="effect-modification-and-interaction.html#cb39-19" tabindex="-1"></a>naive_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(vo2_max <span class="sc">~</span> treatment <span class="sc">+</span> age_group, <span class="at">data =</span> df)</span>
<span id="cb39-20"><a href="effect-modification-and-interaction.html#cb39-20" tabindex="-1"></a></span>
<span id="cb39-21"><a href="effect-modification-and-interaction.html#cb39-21" tabindex="-1"></a>adjusted_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(vo2_max <span class="sc">~</span> treatment <span class="sc">+</span> age_group <span class="sc">+</span> treatment <span class="sc">*</span> age_group, <span class="at">data =</span> df)</span>
<span id="cb39-22"><a href="effect-modification-and-interaction.html#cb39-22" tabindex="-1"></a></span>
<span id="cb39-23"><a href="effect-modification-and-interaction.html#cb39-23" tabindex="-1"></a><span class="fu">summary</span>(naive_model)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = vo2_max ~ treatment + age_group, data = df)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -3.7165 -0.9743 -0.0066  0.9249  3.8438 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 34.17826    0.04955  689.75   &lt;2e-16 ***
## treatment    5.76923    0.05850   98.62   &lt;2e-16 ***
## age_group    2.18968    0.05850   37.43   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.306 on 1997 degrees of freedom
## Multiple R-squared:  0.8527, Adjusted R-squared:  0.8526 
## F-statistic:  5780 on 2 and 1997 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="effect-modification-and-interaction.html#cb41-1" tabindex="-1"></a><span class="fu">summary</span>(adjusted_model)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = vo2_max ~ treatment + age_group + treatment * age_group, 
##     data = df)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -3.0857 -0.6261 -0.0042  0.6543  3.3876 
## 
## Coefficients:
##                     Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)         34.98227    0.04273 818.756  &lt; 2e-16 ***
## treatment            4.05124    0.06246  64.866  &lt; 2e-16 ***
## age_group            0.49082    0.06211   7.903 4.47e-15 ***
## treatment:age_group  3.43225    0.08828  38.880  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.9855 on 1996 degrees of freedom
## Multiple R-squared:  0.9162, Adjusted R-squared:  0.9161 
## F-statistic:  7272 on 3 and 1996 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>If we look only at the naive model without considering effect modification, then we would have incorrectly concluded that the drug impacts young and old people in the same way, adding 5.76 mL/kg/min to a patient’s VO2 max on average.</p>
<p>If we look at the adjusted model considering effect modification, then we see that we more accurately estimate the ground truths. We also have the correct interpretation that the drug’s effect varies depending on whether the patient is young or old. For old people, the drug is estimated to increase the VO2 max by 4.05. For young people, the drug is estimated to increase the VO2 max by 4.05 + 3.43 = 7.48. So the drug is 3.43 units more effective in young people.</p>
<p>The following plot shows how younger patients benefit more from the drug than older patients.</p>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="effect-modification-and-interaction.html#cb43-1" tabindex="-1"></a>df_grouped <span class="ot">&lt;-</span> df <span class="sc">|&gt;</span></span>
<span id="cb43-2"><a href="effect-modification-and-interaction.html#cb43-2" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">age_group =</span> <span class="fu">ifelse</span>(age_group <span class="sc">==</span> <span class="dv">1</span>, <span class="st">&quot;Young&quot;</span>, <span class="st">&quot;Old&quot;</span>))</span>
<span id="cb43-3"><a href="effect-modification-and-interaction.html#cb43-3" tabindex="-1"></a></span>
<span id="cb43-4"><a href="effect-modification-and-interaction.html#cb43-4" tabindex="-1"></a><span class="fu">ggplot</span>(df_grouped, <span class="fu">aes</span>(<span class="at">x =</span> treatment, <span class="at">y =</span> vo2_max, <span class="at">color =</span> age_group)) <span class="sc">+</span></span>
<span id="cb43-5"><a href="effect-modification-and-interaction.html#cb43-5" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">width =</span> <span class="fl">0.1</span>, <span class="at">alpha =</span> <span class="fl">0.4</span>) <span class="sc">+</span></span>
<span id="cb43-6"><a href="effect-modification-and-interaction.html#cb43-6" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">&quot;point&quot;</span>, <span class="at">size =</span> <span class="dv">3</span>, <span class="at">shape =</span> <span class="dv">18</span>) <span class="sc">+</span></span>
<span id="cb43-7"><a href="effect-modification-and-interaction.html#cb43-7" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">&quot;line&quot;</span>, <span class="fu">aes</span>(<span class="at">group =</span> age_group)) <span class="sc">+</span></span>
<span id="cb43-8"><a href="effect-modification-and-interaction.html#cb43-8" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>)) <span class="sc">+</span> </span>
<span id="cb43-9"><a href="effect-modification-and-interaction.html#cb43-9" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Effect Modification: Drug and Age Category&quot;</span>,</span>
<span id="cb43-10"><a href="effect-modification-and-interaction.html#cb43-10" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Treatment (0 = Control, 1 = Drug)&quot;</span>,</span>
<span id="cb43-11"><a href="effect-modification-and-interaction.html#cb43-11" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;VO2 Max (mL/kg/min)&quot;</span>,</span>
<span id="cb43-12"><a href="effect-modification-and-interaction.html#cb43-12" tabindex="-1"></a>       <span class="at">color =</span> <span class="st">&quot;Age Category&quot;</span>) <span class="sc">+</span></span>
<span id="cb43-13"><a href="effect-modification-and-interaction.html#cb43-13" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="Causal-Inference-Graduate_files/figure-html/unnamed-chunk-16-1.png" width="672" /></p>
</div>
<div id="interaction" class="section level2 hasAnchor" number="4.2">
<h2><span class="header-section-number">4.2</span> Interaction<a href="effect-modification-and-interaction.html#interaction" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>When we study interactions, we are trying to understand the joint effect of two or more treatments on a certain outcome. So we answer the causal question “What is the combined effect of treatment 1 and treatment 2 on an outcome?”.</p>
<p>Simulation to Demonstrate Interaction</p>
<p>Let’s say we are interested in understanding the effect of new drug and taking vitamin supplements on a person’s VO2 max. Assume for this example that the patients who take vitamin supplements take the same supplements in the same dosage. In this simulation, the drug increases VO2 max by 4 mL/kg/min, vitamins increase VO2 max by 1.5 mL/kg/min, and taking both the drug and vitamins adds an addition 2.5 mL/kg/min to the VO2 max.</p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="effect-modification-and-interaction.html#cb44-1" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb44-2"><a href="effect-modification-and-interaction.html#cb44-2" tabindex="-1"></a></span>
<span id="cb44-3"><a href="effect-modification-and-interaction.html#cb44-3" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">2000</span></span>
<span id="cb44-4"><a href="effect-modification-and-interaction.html#cb44-4" tabindex="-1"></a></span>
<span id="cb44-5"><a href="effect-modification-and-interaction.html#cb44-5" tabindex="-1"></a>A_1 <span class="ot">&lt;-</span> <span class="fu">rbinom</span>(n, <span class="dv">1</span>, <span class="fl">0.5</span>) <span class="co"># drug</span></span>
<span id="cb44-6"><a href="effect-modification-and-interaction.html#cb44-6" tabindex="-1"></a></span>
<span id="cb44-7"><a href="effect-modification-and-interaction.html#cb44-7" tabindex="-1"></a>A_2 <span class="ot">&lt;-</span> <span class="fu">rbinom</span>(n, <span class="dv">1</span>, <span class="fl">0.5</span>) <span class="co"># vitamin supplementation</span></span>
<span id="cb44-8"><a href="effect-modification-and-interaction.html#cb44-8" tabindex="-1"></a></span>
<span id="cb44-9"><a href="effect-modification-and-interaction.html#cb44-9" tabindex="-1"></a>baseline <span class="ot">&lt;-</span> <span class="dv">35</span> <span class="co"># baseline VO2 max is 35 mL/kg/min</span></span>
<span id="cb44-10"><a href="effect-modification-and-interaction.html#cb44-10" tabindex="-1"></a></span>
<span id="cb44-11"><a href="effect-modification-and-interaction.html#cb44-11" tabindex="-1"></a>vo2_max <span class="ot">&lt;-</span> baseline <span class="sc">+</span> </span>
<span id="cb44-12"><a href="effect-modification-and-interaction.html#cb44-12" tabindex="-1"></a>            <span class="dv">4</span> <span class="sc">*</span> A_1 <span class="sc">+</span> </span>
<span id="cb44-13"><a href="effect-modification-and-interaction.html#cb44-13" tabindex="-1"></a>            <span class="fl">1.5</span> <span class="sc">*</span> A_2 <span class="sc">+</span> </span>
<span id="cb44-14"><a href="effect-modification-and-interaction.html#cb44-14" tabindex="-1"></a>            <span class="fl">2.5</span> <span class="sc">*</span> (A_1 <span class="sc">*</span> A_2) <span class="sc">+</span> </span>
<span id="cb44-15"><a href="effect-modification-and-interaction.html#cb44-15" tabindex="-1"></a>            <span class="fu">rnorm</span>(n, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">1</span>)</span>
<span id="cb44-16"><a href="effect-modification-and-interaction.html#cb44-16" tabindex="-1"></a></span>
<span id="cb44-17"><a href="effect-modification-and-interaction.html#cb44-17" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(vo2_max, A_1, A_2)</span>
<span id="cb44-18"><a href="effect-modification-and-interaction.html#cb44-18" tabindex="-1"></a></span>
<span id="cb44-19"><a href="effect-modification-and-interaction.html#cb44-19" tabindex="-1"></a>naive_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(vo2_max <span class="sc">~</span> A_1 <span class="sc">+</span> A_2, <span class="at">data =</span> df)</span>
<span id="cb44-20"><a href="effect-modification-and-interaction.html#cb44-20" tabindex="-1"></a></span>
<span id="cb44-21"><a href="effect-modification-and-interaction.html#cb44-21" tabindex="-1"></a>adjusted_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(vo2_max <span class="sc">~</span> A_1 <span class="sc">+</span> A_2 <span class="sc">+</span> A_1 <span class="sc">*</span> A_2, <span class="at">data =</span> df)</span>
<span id="cb44-22"><a href="effect-modification-and-interaction.html#cb44-22" tabindex="-1"></a></span>
<span id="cb44-23"><a href="effect-modification-and-interaction.html#cb44-23" tabindex="-1"></a><span class="fu">summary</span>(naive_model)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = vo2_max ~ A_1 + A_2, data = df)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -3.4558 -0.8316  0.0082  0.7735  3.6096 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 34.41251    0.04392  783.61   &lt;2e-16 ***
## A_1          5.26868    0.05184  101.62   &lt;2e-16 ***
## A_2          2.69471    0.05184   51.98   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.158 on 1997 degrees of freedom
## Multiple R-squared:  0.8723, Adjusted R-squared:  0.8722 
## F-statistic:  6820 on 2 and 1997 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="effect-modification-and-interaction.html#cb46-1" tabindex="-1"></a><span class="fu">summary</span>(adjusted_model)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = vo2_max ~ A_1 + A_2 + A_1 * A_2, data = df)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -3.0857 -0.6261 -0.0042  0.6543  3.3876 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 34.98227    0.04273  818.76   &lt;2e-16 ***
## A_1          4.05124    0.06246   64.87   &lt;2e-16 ***
## A_2          1.49082    0.06211   24.00   &lt;2e-16 ***
## A_1:A_2      2.43225    0.08828   27.55   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.9855 on 1996 degrees of freedom
## Multiple R-squared:  0.9075, Adjusted R-squared:  0.9073 
## F-statistic:  6526 on 3 and 1996 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>If we look at the naive model, we would conclude that the drug increase VO2 max by 5.26 and the vitamins increase VO2 max by 2.69. But this isn’t the truth. The naive model doesn’t capture the combined effect of taking both the drug and vitamins, which is capture in the adjusted model using an interaction term.</p>
<p>Based on the adjusted model, we would conclude that the drug increases VO2 max by 4.05, the vitamins increase VO2 max by 1.49, and taking both adds 2.43 mL/kg/min to one’s VO2 max on average. This is closer to the ground truth that we established when explaining the simulation.</p>
<p>This plot shows that taking the drug increases VO2 max, but also taking vitamins with the drug has an combined effect that increases VO2 max.</p>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="effect-modification-and-interaction.html#cb48-1" tabindex="-1"></a><span class="co"># library(ggplot2)</span></span>
<span id="cb48-2"><a href="effect-modification-and-interaction.html#cb48-2" tabindex="-1"></a><span class="co"># library(dplyr)</span></span>
<span id="cb48-3"><a href="effect-modification-and-interaction.html#cb48-3" tabindex="-1"></a></span>
<span id="cb48-4"><a href="effect-modification-and-interaction.html#cb48-4" tabindex="-1"></a>df_grouped <span class="ot">&lt;-</span> df <span class="sc">|&gt;</span></span>
<span id="cb48-5"><a href="effect-modification-and-interaction.html#cb48-5" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">vitamin_group =</span> <span class="fu">ifelse</span>(A_2 <span class="sc">==</span> <span class="dv">1</span>, <span class="st">&quot;Vitamins&quot;</span>, <span class="st">&quot;No Vitamins&quot;</span>))</span>
<span id="cb48-6"><a href="effect-modification-and-interaction.html#cb48-6" tabindex="-1"></a></span>
<span id="cb48-7"><a href="effect-modification-and-interaction.html#cb48-7" tabindex="-1"></a><span class="fu">ggplot</span>(df_grouped, <span class="fu">aes</span>(<span class="at">x =</span> A_1, <span class="at">y =</span> vo2_max, <span class="at">color =</span> vitamin_group)) <span class="sc">+</span></span>
<span id="cb48-8"><a href="effect-modification-and-interaction.html#cb48-8" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">width =</span> <span class="fl">0.1</span>, <span class="at">alpha =</span> <span class="fl">0.4</span>) <span class="sc">+</span></span>
<span id="cb48-9"><a href="effect-modification-and-interaction.html#cb48-9" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">&quot;point&quot;</span>, <span class="at">size =</span> <span class="dv">3</span>, <span class="at">shape =</span> <span class="dv">18</span>) <span class="sc">+</span></span>
<span id="cb48-10"><a href="effect-modification-and-interaction.html#cb48-10" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">&quot;line&quot;</span>, <span class="fu">aes</span>(<span class="at">group =</span> vitamin_group)) <span class="sc">+</span></span>
<span id="cb48-11"><a href="effect-modification-and-interaction.html#cb48-11" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>)) <span class="sc">+</span> </span>
<span id="cb48-12"><a href="effect-modification-and-interaction.html#cb48-12" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Interaction: Drug × Vitamin Supplement&quot;</span>,</span>
<span id="cb48-13"><a href="effect-modification-and-interaction.html#cb48-13" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Treatment (0 = Control, 1 = Drug)&quot;</span>,</span>
<span id="cb48-14"><a href="effect-modification-and-interaction.html#cb48-14" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;VO2 Max (mL/kg/min)&quot;</span>,</span>
<span id="cb48-15"><a href="effect-modification-and-interaction.html#cb48-15" tabindex="-1"></a>       <span class="at">color =</span> <span class="st">&quot;Vitamin Group&quot;</span>) <span class="sc">+</span></span>
<span id="cb48-16"><a href="effect-modification-and-interaction.html#cb48-16" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="Causal-Inference-Graduate_files/figure-html/unnamed-chunk-18-1.png" width="672" /></p>
<p>In this simulation, we learned that when we are interested in measuring the effect of multiple treatments on an outcome, it’s important to consider the combined effect of these treatments. We achieve this by adding an interaction term in our regression model.</p>
</div>
<div id="identifying-interaction" class="section level2 hasAnchor" number="4.3">
<h2><span class="header-section-number">4.3</span> Identifying Interaction<a href="effect-modification-and-interaction.html#identifying-interaction" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Identifying interaction is crucial when studying causal relationships because it tells us whether there is a combined effect of two or more treatments on an outcome. Rather than being a source of bias like confounding, interaction reveals real differences in how subgroups respond to exposures or treatments. Detecting interaction helps researchers understand for whom and under what conditions an intervention works best, allowing for more tailored public health strategies and clinical recommendations.</p>
<p>In our simulation with the drug and vitamin supplements, interaction was present because there was a combined effect of the drug and vitamin supplementation on VO2 max. In particular, patients that took both had the largest increases in VO2 max. By fitting a model with an interaction term between the drug and vitamin use, we were able to identify and quantify this combined interaction effect. Without testing for interaction, we would have incorrectly assumed that the drug and the vitamins independently improve VO2 max.</p>
</div>
<div id="effect-modification-vs-interaction" class="section level2 hasAnchor" number="4.4">
<h2><span class="header-section-number">4.4</span> Effect Modification vs Interaction<a href="effect-modification-and-interaction.html#effect-modification-vs-interaction" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Effect modification and interaction are closely related concepts, but they serve slightly different purposes in causal analysis. The confusing part is when we try to model both effect modification and interaction, we do it the same way with an interaction term in the regression. However, the difference between the two concepts is in the causal questions we are trying to answer.</p>
<p>In effect modification, we are trying to understand how the effect of a single treatment varies based on levels of another factor like age or sex assigned at birth.</p>
<p>In interaction, we are trying to understand the combined effect of two or more treatments such as a drug and vitamin supplementation.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="observational-studies.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="introduction-to-causal-diagrams.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": "https://github.com/fbargaglistoffi/causal_inference_graduate/edit/main/04_effect_modification.Rmd",
    "text": "Edit"
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": "https://github.com/fbargaglistoffi/causal_inference_graduate/blob/main/04_effect_modification.Rmd",
    "text": null
  },
  "download": null,
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
